FROM python:3.10

WORKDIR /app
COPY . .

RUN pip install --no-cache-dir \
    flask \
    google-api-python-client \
    google-auth \
    google-auth-oauthlib \
    google-auth-httplib2

CMD ["python", "main.py"]
